### ISSUE TITLE
你的屏幕是长排线还是短排线？

### ISSUE THREAD

**Issue by AXFOX** [Admin-233/displayDrivers#1]
4in2 长短排线是俩屏幕，驱动方式不太一样。我试了试本仓库的4in2b0可以正常驱动我的短排线，所以盲猜你也是短排线，长排线的我没拿到就不管咯。（我俩都是完全一样的短排线。）

**Comment by Admin-233** [comment]
也没见过长排线多长，应该是短排线了，量了一下是1.2cm长
